version: '3.8'

services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes
    restart: always

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db
    restart: always
    environment:
      - MONGO_INITDB_DATABASE=social-media-scheduler

volumes:
  redis-data:
  mongodb-data: 
